### ISSUE TITLE
why tune n here?isn't n the batch size?

### ISSUE THREAD

**Issue by andylida** [vincentherrmann/pytorch-wavenet#30]
here is a segment of wavenet_modules:
`     
l_old = int(round(l / dilation_factor)) 
`     
`     
n_old = int(round(n * dilation_factor))  
`     
`     
   l = math.ceil(l * init_dilation / dilation)  
`     
`     
   n = math.ceil(n * dilation / init_dilation)  
`

i can't figure out why the batch size changed,
i think by this way,the net would be sensitive to the order of the data
can someone help with this? thanks

**Comment by wangpengabc** [comment]
Have you figured out? Can you explain why the n is changed/recalculate
