### ISSUE TITLE
Not able to listen to generated samples

### ISSUE THREAD

**Issue by arijit17** [vincentherrmann/pytorch-wavenet#8]
Hi!

I'm not able to play these files: https://github.com/vincentherrmann/pytorch-wavenet/tree/master/generated_samples

**Comment by vincentherrmann** [comment]
Did you download these files? I don't think there is a way to listen to audio files directly on GitHub.

**Comment by arijit17** [comment]
Yes, I downloaded the files and I'm not able to play with common media players. Which player are you using?

**Comment by arijit17** [comment]
Oh OK works. I needed to check-out the repo
