### ISSUE TITLE
RuntimeError: Input type (CUDAFloatTensor) and weight type (CPUFloatTensor) should be the same

### ISSUE THREAD

**Issue by krishnakt031990** [vincentherrmann/pytorch-wavenet#9]
I am getting this error on runtime. Does any one know what the problem might be?

**Comment by vincentherrmann** [comment]
Hi! Looks like the model is on the GPU, but the data is on the CPU. The [WaveNetTrainer class](https://github.com/vincentherrmann/pytorch-wavenet/blob/30ad85577cddccdce506ac27ee33e22f55344c63/wavenet_training.py#L20) has the attribute `dtype` which should be `torch.cuda.FloatTensor` if you're using a GPU. Are you running the train_script.py or the Jupyter notebook?

**Comment by krishnakt031990** [comment]
JUPYTER notebook which is deployed on the GPU AWS instance and accusing it from my Mac

**Comment by pranavdheram** [comment]
Hello, how did you fix this error?

**Comment by sylvchev** [comment]
Adding a `model.cuda()` before training solve the issue.
